config/routes.rb
Splurty::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

root 'quotes#index'
resources :quotes
get 'about', :to => 'quotes#about'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/quote.rb
require 'obscenity/active_model'

class Quote < ActiveRecord::Base
	validates :saying, :presence => true, :length => { :maximum => 140, :minimum => 3 }, obscenity: { sanitize: true, replacement: :garbled }
	validates :author, :presence => true, :length => { :maximum => 50, :minimum => 3}

	def next
	  self.class.where("id > ?", id).first
  end

  def previous
	  self.class.where("id < ?", id).last
  end

	def unique_tag
		abbr = self.author.split(" ").collect do |sub_string|
			sub_string[0]
	  end

		abbr.join + '#' + self.id.to_s
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
	# def index
	# 	@quote = Quote.order("RANDOM()").first
	# end

	def index
		@quote = Quote.order('id DESC').all
	end

	def create
		@quote = Quote.create(quote_params)
		if @quote.invalid?
			flash[:error] = '<strong>Could not save!</strong> The data you entered is invalid.'
		else 
			flash[:notice] = '<strong>Thanks for your submission!</strong>'
		    $client.update("#YKYWAASW #{@quote.saying} -#{@quote.author}")
		end
		redirect_to root_path
	end

	def show
		@quote = Quote.where(:id => params[:id]).first
		if @quote.blank?
			render :text => "Not Found", :status => :not_found
		end
		respond_to do |format|
			format.html
			format.json {render json: @quote}
		end
	end


	def about
	end


	private


	def quote_params
		params.require(:quote).permit(:saying, :author)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>You Know You Work at a Startup When...</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <script src="http://desandro.github.io/masonry/jquery.masonry.min.js"></script>
  <%= csrf_meta_tags %>


<script>
  <!-- GOOGLE ANALYTICS CODE -->
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60948534-1', 'auto');
  ga('send', 'pageview');

</script>

</head>
<body>
  <header>
  	<%= link_to root_path do %>
  		<h1>You Know You Work at a Startup When...</h1>
  	<% end %>
  </header>

  <br class="clear" />

<div class="container-fluid">
	<% if flash[:error].present? %>
		<div class="col-md-10 col-md-offset-1 alert alert-danger text-center">
			<%= flash[:error].html_safe %>
		</div>
    <% end %>

    <% if flash[:alert].present? %>
		<div class="col-md-10 col-md-offset-1 alert alert-danger text-center">
			<%= flash[:alert].html_safe %>
		</div>
    <% end %>

	<% if flash[:notice].present? %>
	  <div class="col-md-10 col-md-offset-1 alert alert-success alert-dismissible text-center fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	  	<%= flash[:notice].html_safe %>
	  </div>
	<% end %>

	<%= yield %>
</div>

<div class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <div class="pull-left navbar-text site-credit">
    	A quick project by <%= link_to 'Danny Nathan', about_path %>.  |  © 2015
    </div>
    <div class="pull-right">
      <%= link_to root_path do%>
        <span class="glyphicon glyphicon-home">
       <% end %>
      <%= link_to 'http://twitter.com/ykywaasw', :target => '_blank' do %>
        <%= image_tag 'twitter.svg', :class => 'social-button' %>
      <% end %>
    </div>
  </div>
</div>

</body>
</html>

app/views/quotes/about.html.erb
<br />
<div class="about col-xs-12 col-sm-8 col-sm-offset-2">
	<h2>What is this?</h2>

	<p><strong>You Know You Work at a Startup When...</strong> was built by <a href="http://1amongmany.com">Danny Nathan</a>, an Entrepreneur, Product Designer, and Creative Strategist. After 10+ years of working with brands and startups, Danny decided it was time to learn how to code. He is working through the web development intensive at <a href="http://thefirehoseproject.com">The Firehose Project</a>. This is his first project.</p>

	<br />

	<p><strong>Here's Where to Find Danny:</strong>
		<ul>
			<li>Reach me <a href="mailto:danny@amongmany.com" target="blank">via email</a></li>
			<li>Shout <a href="http://twitter.com/amongmany" target="blank">on Twitter</a></li>
			<li>Find me <a href="http://linkedin.com/in/amongmany" target="blank">on LinkedIn</a></li>
			<li>Peek at <a href="http://1amongmany.com" target="blank">my Portfolio</a></li>
			<li>Peruse <a href="http://amongmany.com" target="blank">my Tumblr</a></li>
			<li>View <a href="http://shotsamongmany.com" target="blank">my Photography</a></li>
		</ul></p>
</div>

app/views/quotes/index.html.erb
<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix centered">
	<div class="submission-box item">
  		<h2>Share Your Startup Wisdom:</h2>
  		<%= simple_form_for Quote.new do |f| %>
    	<%= f.input :saying, label: 'You Know You Work at a Startup When...', placeholder: 'you function on 5 or less hours of sleep, daily.' %>
    	<%= f.input :author, label: 'Your Name:', placeholder: 'or you could be "Anonymous."' %>
    	<%= f.submit 'Submit', :class => 'btn btn-danger pull-right' %>
  		<% end %>
	</div>

	<% @quote.each do |quote| %>
		<div class="card item">
			<div class="headline"> 
				<%= link_to quote_path(quote.id) do %> 
				 Insight #<%= quote.id %>:
				 <% end %>
			</div>

			<h2 class="intro">
				<span>You know you work at a startup when...</span>
			</h2>

			<h1><%= quote.saying %></h1>
			<h2 class="sign-off pull-right">-<%= quote.author %></h2>
		</div>
	<% end %>
</div>

app/views/quotes/show.html.erb
<table class="col-xs-10 col-xs-offset-1">
	<tr>
	<td>
		<% unless @quote == Quote.first %>
			<%= link_to quote_path(@quote.previous) do %>
				<%= image_tag 'back.png', :class => 'back pull-right' %>
			<% end %>
	  <% end %>
	</td>

	<td class="show-card">
		<div class="headline">
			 Enlightened Insight, Number <%= @quote.id %>:
		</div>

		<h2>
			<span>You know you work at a startup when...</span>
		</h2>

		<h1><%= @quote.saying %></h1>
		<h2 class="pull-right">-<%= @quote.author %></h2>
	</td>

		<td>
			<% unless @quote == Quote.last %>
				<%= link_to quote_path(@quote.next) do %>
					<%= image_tag 'forward.png', :class => 'next' %>
				<% end %>
			<% end %>
		</td>
  </tr>
</table>